version: '3.8'

services: 
    rabbitmq:
        image: rabbitmq:3-management
        hostname: my-rabbit-mq
        container_name: rabbit-mq
        networks: 
            - rabbitmq
        environment: 
            "RABBITMQ_DEFAULT_USER": "user"
            "RABBITMQ_DEFAULT_PASS": "password"
        ports: 
            - 15672:15672
            - 5672:5672

            
networks: 
    rabbitmq: